### ISSUE TITLE
New developments for 29/5

### ISSUE THREAD

**Issue by vnemes** [vnemes/BLECar#25]
### The following points are still open:
@dnutiu 
+ Connect REST endpoint to dbus service for GPS, returning the following values in json:
````
lat : gps.latitude
lat_dir : gps.lat_dir
long : gps.longitude
long_dir : gps.lon_dir
alt : gps.altitude
alt_unit : gps.altitude_units
````
+ Create REST endpoint /administration/service for enabling/disabling services, accepting a POST request with the format
````
service_name : desired_status
````
+ Create a HTML page to be returned when accessing /administration endpoints, in which services can be enabled/disabled and OTA upgrade can be performed. 
+ Enable BasicAuth

@vnemes
+ Android App: Create DialogBox showing a map with the current position
+ Create Sensor Class for the GPS Sensor
+ Configure HTML requests to use BasicAuth

**Comment by dnutiu** [comment]
> Create REST endpoint /administration/service for enabling/disabling services, accepting a POST request with the format

This is done, url is services. Will be changed to service in other commit.
You can check administration/views.py to see how it works.

> Create a HTML page to be returned when accessing /administration endpoints, in which services can be enabled/disabled and OTA upgrade can be performed.

OTA part is done.

**Comment by vnemes** [comment]
Auth for rest endpoints can be postponed to a later release.
Great avatar, way better than the previous one.

Perhaps a css for the ota html could be done?

**Comment by dnutiu** [comment]
Done /w the css.

**Comment by dnutiu** [comment]
After we fix our D-Bus bug we can safely enable basic auth I think.
